apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenpo-ivr
  namespace: tenpo-ivr
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: tenpo-ivr
  template:
    metadata:
      namespace: tenpo-ivr
      labels:
        app: tenpo-ivr
        version: v1
    spec:
      containers:
        - name: tenpo-ivr
          image: _IMAGE_
          ports:
            - containerPort: 80
          resources:
              requests:
                cpu: 300m
                memory: 300Mi
              limits:
                cpu: 700m
                memory: 700Mi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 120
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 120
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3
          env:
            - name: COMMIT_SHA
              value: "_COMMIT_SHA_"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: databasecredentials
                  key: tenpo_ivr_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: databasecredentials
                  key: tenpo_ivr_password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: databasecredentials
                  key: tenpo_ivr_host
            - name: SERVER_PORT
              value: "80"
            - name: BO_URL
              value: "_BO_URL_"
          imagePullPolicy: Always
      imagePullSecrets:
        - name: tenpo-ivr-registry